name: Test and Build and Push Docker Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
        env:
          DB_DATABASE: ":memory:"
      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install NPM dependencies
        run: npm install --include=dev --no-audit --no-fund
      - name: Build assets
        run: npm run build
      - name: Execute tests (Feature tests) via PHPUnit/Pest
        run: php artisan test
        env:
          DB_DATABASE: ":memory:"

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner	}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          build-args: |
            REPO=${{ github.repository }}
            VER=${{ github.run_number }}
          platforms: linux/amd64
          # linux/386
          # linux/arm/v7
          # linux/arm64
          push: true
          tags: ${{ github.repository }}:latest, ${{ github.repository }}:${{ github.run_number }}
